data_dict = {
    'Name': '',
    'Vorname': '',
    'Geburtsdatum': '',
    'Geburtsland': '',
    'Geburtsort': '',
    'Staatsangehorigkeit': '',
    'Praktische Hinweise zur Durchfuhrung der Anhorung': '',
    'Im Auftrag': '',
    'Geschlecht': '',
    'Familienstand': '',
    'korperlich': '',
    'seelisch': '',
    'geistig': '',
    'Sinnesbeeintrachtigung': '',
    'Alleinerziehende': '',
    'Schwangere': '',
    'alter als 65 Jahre': '',
    'Verlust oder Trennung von engen Familienangehorigen': '',
    'Soziale Isolation': '',
    'Erfahrungen mit korperlicher oder seelischer Gewalt wahrend Flucht oder Aufenthalt': '',
}